services:
    Eliberty\Bundle\FormElementTypeBundle\Twig\Extension\FormExtension:
        arguments: ["@twig.form.renderer"] 
        tags: [{ name: twig.extension }]
    Eliberty\Bundle\FormElementTypeBundle\Form\CheckboxToggleType:
        tags: [{ name: form.type, alias: eliberty_checkboxtoggle }]
    Eliberty\Bundle\FormElementTypeBundle\Form\FieldsetType:
        tags: [{ name: form.type, alias: eliberty_fieldset }]
    Eliberty\Bundle\FormElementTypeBundle\Form\CheckboxSwitchType:
        tags: [{ name: form.type, alias: eliberty_checkboxswitch }]
    Eliberty\Bundle\FormElementTypeBundle\Form\BooleanType:
        tags: [{ name: form.type, alias: eliberty_boolean }]
    Eliberty\Bundle\FormElementTypeBundle\Form\InversedBooleanType:
        tags: [{ name: form.type, alias: eliberty_inversed_boolean }]
    Eliberty\Bundle\FormElementTypeBundle\Form\MarkdownEditorType:
        tags: [{ name: form.type, alias: eliberty_markdown_editor }]
    Eliberty\Bundle\FormElementTypeBundle\Form\MultiSelectType:
        tags: [{ name: form.type, alias: eliberty_multiselect }]
    Eliberty\Bundle\FormElementTypeBundle\Form\DatePickerType:
        tags: [{ name: form.type, alias: eliberty_datepicker }]
    Eliberty\Bundle\FormElementTypeBundle\Form\TagsType:
        tags: [{ name: form.type, alias: eliberty_tags }]
    Eliberty\Bundle\FormElementTypeBundle\Form\FileUploadType:
        tags: [{ name: form.type, alias: eliberty_file_upload }]
    Eliberty\Bundle\FormElementTypeBundle\Form\RestChoiceType:
        tags: [{ name: form.type, alias: eliberty_rest_choice }]
    Eliberty\Bundle\FormElementTypeBundle\Form\BntChoiceType:
        tags: [{ name: form.type, alias: eliberty_bnt_choice }]
    Eliberty\Bundle\FormElementTypeBundle\Form\ExpandedType:
        tags: [{ name: form.type, alias: eliberty_expanded }]
    Eliberty\Bundle\FormElementTypeBundle\Form\ChosenType:
        tags: [{ name: form.type, alias: eliberty_chosen }]
    Eliberty\Bundle\FormElementTypeBundle\Form\ChosenEntityType:
        tags: [{ name: form.type, alias: eliberty_chosen_entity }]
    Eliberty\Bundle\FormElementTypeBundle\Form\KeycardSkidataType:
        tags: [{ name: form.type, alias: eliberty_keycard_skidata }]
    Eliberty\Bundle\FormElementTypeBundle\Form\KeycardTeamaxessType:
        tags: [{ name: form.type, alias: eliberty_keycard_teamaxess }]
    Eliberty\Bundle\FormElementTypeBundle\Form\KeycardAlfiType:
        tags: [{ name: form.type, alias: eliberty_keycard_alfi }]
    Eliberty\Bundle\FormElementTypeBundle\Form\KeycardOpenType:
        tags: [{ name: form.type, alias: eliberty_keycard_open }]
    Eliberty\Bundle\FormElementTypeBundle\Form\DateTimePickerType:
        tags: [{ name: form.type, alias: eliberty_datetime_picker }]
    Eliberty\Bundle\FormElementTypeBundle\Form\IntegerType:
        tags: [{ name: form.type, alias: eliberty_integer }]
    Eliberty\Bundle\FormElementTypeBundle\Form\TextMaskType:
        tags: [{ name: form.type, alias: eliberty_textmask }]
    Eliberty\Bundle\FormElementTypeBundle\Form\DecimalType:
        tags: [{ name: form.type, alias: eliberty_decimal }]
    Eliberty\Bundle\FormElementTypeBundle\Form\JsonType:
        tags: [{ name: form.type, alias: eliberty_json }]
    Eliberty\Bundle\FormElementTypeBundle\Form\PolyCollectionType:
        tags:
            - { name: form.type, alias: eliberty_polycollection}
    Eliberty\Bundle\FormElementTypeBundle\Form\EntityHiddenType:
         arguments: ["@doctrine.orm.entity_manager"]
         tags:
            - { name: form.type, alias: eliberty_entity_hidden }
    Eliberty\Bundle\FormElementTypeBundle\Form\ColorPickerType:
        tags: [{ name: form.type, alias: eliberty_colorpicker }]
    Eliberty\Bundle\FormElementTypeBundle\Form\PhoneNumberType:
        tags: [{ name: form.type, alias: eliberty_phonenumber }]
