parameters:
#    eliberty_form.example.class: Eliberty\FormBundle\Example

services:

    eliberty.form.type.boolean:
        class: Eliberty\Bundle\FormElementTypeBundle\Form\BooleanType
        tags: [{ name: form.type, alias: eliberty_boolean }]
    eliberty.form.type.markdown.editor:
        class: Eliberty\Bundle\FormElementTypeBundle\Form\MarkdownEditorType
        tags: [{ name: form.type, alias: eliberty_markdown_editor }]
    eliberty.form.type.multiselect:
        class: Eliberty\Bundle\FormElementTypeBundle\Form\MultiSelectType
        tags: [{ name: form.type, alias: eliberty_multiselect }]
    eliberty.form.type.datepicker:
        class: Eliberty\Bundle\FormElementTypeBundle\Form\DatePickerType
        tags: [{ name: form.type, alias: eliberty_datepicker }]
    eliberty.form.type.tags:
        class: Eliberty\Bundle\FormElementTypeBundle\Form\TagsType
        tags: [{ name: form.type, alias: eliberty_tags }]
    eliberty.form.type.file.upload:
        class: Eliberty\Bundle\FormElementTypeBundle\Form\FileUploadType
        tags: [{ name: form.type, alias: eliberty_file_upload }]
    eliberty.form.type.choice_rest:
        class: Eliberty\Bundle\FormElementTypeBundle\Form\RestChoiceType
        tags: [{ name: form.type, alias: eliberty_rest_choice }]
    eliberty.form.type.choice_bnt:
        class: Eliberty\Bundle\FormElementTypeBundle\Form\BntChoiceType
        tags: [{ name: form.type, alias: eliberty_bnt_choice }]
    eliberty.form.type.expanded:
        class: Eliberty\Bundle\FormElementTypeBundle\Form\ExpandedType
        tags: [{ name: form.type, alias: eliberty_expanded }]
    eliberty.form.type.chosen:
        class: Eliberty\Bundle\FormElementTypeBundle\Form\ChosenType
        tags: [{ name: form.type, alias: eliberty_chosen }]
    eliberty.form.type.chosen.entity:
        class: Eliberty\Bundle\FormElementTypeBundle\Form\ChosenEntityType
        tags: [{ name: form.type, alias: eliberty_chosen_entity }]
    eliberty.form.type.keycard.skidata:
        class: Eliberty\Bundle\FormElementTypeBundle\Form\KeycardSkidataType
        tags: [{ name: form.type, alias: eliberty_keycard_skidata }]
    eliberty.form.type.keycard.teamaxess:
            class: Eliberty\Bundle\FormElementTypeBundle\Form\KeycardTeamaxessType
            tags: [{ name: form.type, alias: eliberty_keycard_teamaxess }]

    ##Defined form polymorphe collections
    eliberty.form.polycollection_type:
        class: Eliberty\Bundle\FormElementTypeBundle\Form\PolyCollectionType
        tags:
            - { name: form.type, alias: eliberty_polycollection}

    eliberty.form.type.entity_hidden:
         class: Eliberty\Bundle\FormElementTypeBundle\Form\EntityHiddenType
         arguments: ["@doctrine.orm.entity_manager"]
         tags:
         - { name: form.type, alias: eliberty_entity_hidden }





